version: 0.1.0.{build}
os: Visual Studio 2019
environment:
  ASPNETCORE_ENVIRONMENT: appveyor
  COVERALLS_REPO_TOKEN:
    secure: xWD+a2Pkd6bpOW7Xv9XxczN2qNh+PUqiu6o50lbM3V+Vg4Mq4r28WbYQ3JJj5g68

init:
  - git config --global core.autocrlf input

install:
  - ps: Import-Module "$env:ProgramFiles\Azure Cosmos DB Emulator\PSModules\Microsoft.Azure.CosmosDB.Emulator"
  - ps: Start-CosmosDbEmulator
  - dotnet tool install --global coveralls.net

dotnet_csproj:
  patch: true
  file: 'build\version.props'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

configuration: Release

build_script:
  - dotnet pack Cosmos.Identity.sln --configuration Release --include-symbols --include-source

test_script:
  - dotnet test Cosmos.Identity.sln --configuration Release --collect:"XPlat Code Coverage" --settings coverlet.runsettings

after_test:
  - ps: .\coveralls.ps1

artifacts:
- path: artifacts\*.*nupkg
  name: Packages

deploy:
- provider: Environment
  name: MyGet